:memo: Update codegen for latest release
Kamino-Finance/klend-sdk pull request #37
Opened 2024-05-08 15:46 UTC by andreihrs

### Checklist

- [] if I'm working with the latest farms.so version, I have modified the so with the latest one from master
- [] if I'm working with the latest kamino_lending.so version, I have modified the so with the latest one from master

2024-05-08 15:47 UTC, peroxy approved these changes

2024-05-08 16:00 UTC, elliotkennedy requested changes

2024-05-08 16:00 UTC, elliotkennedy commented on src/idl_codegen/zero_padding/ObligationZP.ts
> +      borrowingDisabled: dec.borrowingDisabled,
You need to ensure the new fields are added by copying the generated code to line #69 of this file - otherwise the length of the `ObligationZP` will not include the new field and we will truncate it from the obligations getPA query

2024-05-08 16:02 UTC, elliotkennedy commented on src/idl_codegen/zero_padding/ObligationZP.ts
> +      borrowingDisabled: dec.borrowingDisabled,
See how the length is used here - https://github.com/Kamino-Finance/klend-sdk/blob/master/src/classes/market.ts#L513

So it is important that the new fields are added to the borsh layout, sorry I should add tests for this

2024-05-09 09:20 UTC, elliotkennedy approved these changes
Nice one lgtm

2024-05-13 07:44 UTC, merged